### ISSUE TITLE
Cannot find an overload for "TcpClient" and the argument count "2".

### ISSUE THREAD

**Issue by DavidTik** [machine1337/window-rat#2]
Hi,
Just tried to run generated .ps1 script but it failes, than tried to compile with ps2exe than i get errors:
Cannot find an overload for "TcpClient" and the argument count "2".
You cannot call a method on a null-vauled expression 4 times
![PS-Error](https://user-images.githubusercontent.com/52661622/128077001-60b9e9d0-ca07-4976-9c0b-b39b27a34416.png)

**Comment by machine1337** [comment]
@DavidTik Don't run payload.ps1....First run the script enter lhost and lport and rest of the tool will generate another payload for you by the name of bypass.ps1 and that will be your final payload.

**Comment by DavidTik** [comment]
Ooo, sory my mistake, i went directly to payloads folder instead using bypass.ps1. Thank you. Good job with the script. Thank you !
